### ISSUE TITLE
When an app running a job restarts, the job is not retried

### ISSUE THREAD

**Issue by seliverro** [hangfire-postgres/Hangfire.PostgreSql#321] opened 2023-08-28 16:54 UTC
After the app running the job restarts I can see the job in admin console with the next message: _the job was aborted – it is processed by server aom23n:20248:b37ce3da-82ce-4fb1-805b-3617257d0979 which is not in the [active servers](http://localhost/hangfire/servers) list for now. It will be retried automatically after invisibility timeout, but you can also re-queue or delete it manually._ 

But despite I set InvisibilityInterval to 1 minute, the job is continuing staying in this state for already 2 hours. Can anything 
help with that?

How I configure postgre options is:
```
            var opt = new PostgreSqlStorageOptions()
            {
                DistributedLockTimeout = TimeSpan.FromSeconds(60), 
                InvisibilityTimeout = new TimeSpan(0, 1, 0),
                JobExpirationCheckInterval = new TimeSpan(0, 1, 0)
            };
```

I'm currently using Hangfire 1.8.5 and hangfire.postgreSql 1.20.2

**Comment by dmitry-vychikov** [comment] 2023-08-29 06:57
Hi @seliverro 

I have a feeling that I've run into similar behavior several years ago. At that time, we created our own background process that would clean up stuck jobs. I will double check it when I get home later today.

Also, it will be useful to have:

1) can you please share a screenshot of your dashboard? I would like to double check job status.

2) do you see any hangfire related errors or warning in logs? 

3) can you prepare a repro?

**Comment by seliverro** [comment] 2023-08-29 07:59
Hi @dmitry-vychikov thanks for answering shortly!

Actually I need my jobs to be retried rather than just have a possibility to kill them. Because they are fire and forget jobs containing data I don't want to lose. Otherwise I'll have to reorganize my approach of how to have guarantees my jobs will be run :)

1. The dashboard screen:
<img width="945" alt="image" src="https://github.com/hangfire-postgres/Hangfire.PostgreSql/assets/3530752/9e6fc730-c715-49e9-822e-fd0bfdfc332c">

2. Nothing special in logs, they look like:
```
{"timestamp":"2023-08-29T10:48:50.5678769+03:00","severity":"Information",""context":"Hangfire.PostgreSql.PostgreSqlStorage","message":"Start installing Hangfire SQL objects..."}
{"timestamp":"2023-08-29T10:48:50.6323447+03:00","severity":"Information",""context":"Hangfire.PostgreSql.PostgreSqlStorage","message":"Hangfire SQL objects installed."}
{"timestamp":"2023-08-29T10:48:52.4354834+03:00","severity":"Information",""context":"Hangfire.BackgroundJobServer","message":"Starting Hangfire Server using job storage: 'PostgreSQL Server: Host: localhost, DB: smth, Schema: hangfire'"}
{"timestamp":"2023-08-29T10:48:52.4370082+03:00","severity":"Information",""context":"Hangfire.BackgroundJobServer","message":"Using the following options for SQL Server job storage:"}
{"timestamp":"2023-08-29T10:48:52.4381792+03:00","severity":"Information",""context":"Hangfire.BackgroundJobServer","message":"    Queue poll interval: 00:00:15."}
{"timestamp":"2023-08-29T10:48:52.4385598+03:00","severity":"Information",""context":"Hangfire.BackgroundJobServer","message":"    Invisibility timeout: 00:01:00."}
{"timestamp":"2023-08-29T10:48:52.4393343+03:00","severity":"Information",""context":"Hangfire.BackgroundJobServer","message":"Using the following options for Hangfire Server:\r\n    Worker count: 1\r\n    Listenin
g queues: 'default'\r\n    Shutdown timeout: 00:00:15\r\n    Schedule polling interval: 00:00:15"}
{"timestamp":"2023-08-29T10:48:52.4995877+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop BackgroundServerProcess:f0a48938 has started in 7.4786 ms"}
{"timestamp":"2023-08-29T10:48:52.5012989+03:00","severity":"Information",""context":"Microsoft.Hosting.Lifetime","message":"Application started. Press Ctrl+C to shut down."}
{"timestamp":"2023-08-29T10:48:52.5023644+03:00","severity":"Information",""context":"Microsoft.Hosting.Lifetime","message":"Hosting environment: Development"}
{"timestamp":"2023-08-29T10:48:52.5026065+03:00","severity":"Information",""context":"Microsoft.Hosting.Lifetime","message":"Content root path: smth"}
{"timestamp":"2023-08-29T10:48:52.5296907+03:00","severity":"Information",""context":"Hangfire.Server.BackgroundServerProcess","message":"Server aom23n:23708:0242b0f8 successfully announced in 26.1019 ms"}
{"timestamp":"2023-08-29T10:48:52.5345781+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop ServerHeartbeatProcess:f5c97779 has started in 3.4457 ms"}
{"timestamp":"2023-08-29T10:48:52.5349366+03:00","severity":"Information",""context":"Hangfire.Server.BackgroundServerProcess","message":"Server aom23n:23708:0242b0f8 is starting the registered dispatchers: ServerW
atchdog, ServerJobCancellationWatcher, ExpirationManager, CountersAggregator, Worker, DelayedJobScheduler, RecurringJobScheduler..."}
{"timestamp":"2023-08-29T10:48:52.5379420+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop ServerWatchdog:756efac1 has started in 2.537 ms"}
{"timestamp":"2023-08-29T10:48:52.5404317+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop ServerJobCancellationWatcher:c434fb41 has started in 4.451 ms"}
{"timestamp":"2023-08-29T10:48:52.5433587+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop ExpirationManager:9355748e has started in 2.9251 ms"}
{"timestamp":"2023-08-29T10:48:52.5458400+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop CountersAggregator:b98497ef has started in 4.7349 ms"}
{"timestamp":"2023-08-29T10:48:52.5483485+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop Worker:ab3c18d1 has started in 5.0874 ms"}
{"timestamp":"2023-08-29T10:48:52.5505002+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.CountersAggregator","message":"Aggregating records in 'Counter' table..."}
{"timestamp":"2023-08-29T10:48:52.5512232+03:00","severity":"Information",""context":"Hangfire.Server.BackgroundServerProcess","message":"Server smth:23708:0242b0f8 all the dispatchers started"}
{"timestamp":"2023-08-29T10:48:52.5512537+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop DelayedJobScheduler:7f437edc has started in 5.5023 ms"}
{"timestamp":"2023-08-29T10:48:52.5538762+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'aggregatedcounter'..."}
{"timestamp":"2023-08-29T10:48:52.5540565+03:00","severity":"Debug",""context":"Hangfire.Processing.BackgroundExecution","message":"Execution loop RecurringJobScheduler:0e73e4fe has started in 5.7131 ms"}
{"timestamp":"2023-08-29T10:48:52.5945081+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'counter'..."}
{"timestamp":"2023-08-29T10:48:52.6110736+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'job'..."}
{"timestamp":"2023-08-29T10:48:52.6264417+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'list'..."}
{"timestamp":"2023-08-29T10:48:52.6425401+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'set'..."}
{"timestamp":"2023-08-29T10:48:52.6652395+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'hash'..."}
{"timestamp":"2023-08-29T10:48:52.7524067+03:00","severity":"Debug",""context":"Hangfire.Server.RecurringJobScheduler","message":"1 recurring job(s) processed by scheduler."}
{"timestamp":"2023-08-29T10:49:07.8175448+03:00","severity":"Debug",""context":"Hangfire.Server.RecurringJobScheduler","message":"1 recurring job(s) processed by scheduler."}
{"timestamp":"2023-08-29T10:49:22.5725160+03:00","severity":"Debug",""context":"Hangfire.Server.ServerHeartbeatProcess","message":"Server aom23n:23708:0242b0f8 heartbeat successfully sent"}
{"timestamp":"2023-08-29T10:49:52.6021755+03:00","severity":"Debug",""context":"Hangfire.Server.ServerHeartbeatProcess","message":"Server aom23n:23708:0242b0f8 heartbeat successfully sent"}
{"timestamp":"2023-08-29T10:49:52.7421913+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'aggregatedcounter'..."}
{"timestamp":"2023-08-29T10:49:52.7512825+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'counter'..."}
{"timestamp":"2023-08-29T10:49:52.7625312+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'job'..."}
{"timestamp":"2023-08-29T10:49:52.7721109+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'list'..."}
{"timestamp":"2023-08-29T10:49:52.7833750+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'set'..."}
{"timestamp":"2023-08-29T10:49:52.7928202+03:00","severity":"Debug",""context":"Hangfire.PostgreSql.ExpirationManager","message":"Removing outdated records from table 'hash'..."}
{"timestamp":"2023-08-29T10:50:07.9263199+03:00","severity":"Debug",""context":"Hangfire.Server.RecurringJobScheduler","message":"1 recurring job(s) processed by scheduler."}
{"timestamp":"2023-08-29T10:50:22.6111213+03:00","severity":"Debug",""context":"Hangfire.Server.ServerHeartbeatProcess","message":"Server aom23n:23708:0242b0f8 heartbeat successfully sent"}
{"timestamp":"2023-08-29T10:50:52.6398725+03:00","severity":"Debug",""context":"Hangfire.Server.ServerHeartbeatProcess","message":"Server aom23n:23708:0242b0f8 heartbeat successfully sent"}
```

3. What kind of repro do you mean, a video?

**Comment by azygis** [comment] 2023-08-29 08:03
Repro, as in a small runnable application that can reliably and consistently reproduce the problem.

**Comment by seliverro** [comment] 2023-08-29 11:29
[TestHangfire.zip](https://github.com/hangfire-postgres/Hangfire.PostgreSql/files/12463966/TestHangfire.zip)
here it is!

**Comment by seliverro** [comment] 2023-08-30 07:49
By the way, I would say that InvisibilityTimeout doesn't work at all. Currently I'm testing a case whern a long job must be retried after InvisibilityTimeout is over and the job is still in progress. And it is not retried.

**Comment by dmitry-vychikov** [comment] 2023-08-30 17:46
Hi @seliverro 

I took a brief look at your repro. Here are some thoughts.

1)
```c#
builder.Services.AddHangfireServer(x => { x.WorkerCount = 1; }); 
```

You have only 1 worker on hangfire server.  With such a configuration, you won't be able to run more than `1 job at a time`.


2) 

```c#
internal class SendTournamentRewards
{
    [DisableConcurrentExecution(timeoutInSeconds: 60)]
    [AutomaticRetry(Attempts = 5, OnAttemptsExceeded = AttemptsExceededAction.Fail)]
    public void Exec()
```

You use `[DisableConcurrentExecution]` attribute which also restricts concurrency to a single worker per job type.

**Suggested next steps:**
- Increase WorkerCount to 5 or 10
- Remove `DisableConcurrentExecution` attribute
- `DistributedLockTimeout = TimeSpan.FromSeconds(60)` -> try reducing it to `10 seconds`
    - This might be another reason why job cannot be picked up
- If nothing helps, please include additional screenshots from hangfire dashboard
    - `Servers` tab
    - `Details` page for any job that got stuck
 

> At that time, we created our own background process that would clean up stuck jobs. I will double check it when I get home later today.

Sorry, I'm not able to recover that source code anymore.
But I also looked at Hangire.Postgres dequeuing implementation, and it seems correct.
I bet your issues are caused by configuration.

**Comment by seliverro** [comment] 2023-08-31 07:18
Hi @dmitry-vychikov , it looks like you correct. My configuration was a very custom scenario when 

- DistributedLockTimeout was 1 minute and
- job schedule was every one minute 
- and it was only one worker

so only one job could be in progress at a time and there was no delay until running of a next scheduled job. What was not clear for me is that retrying of failed jobs are of lower priority that running new scheduled ones. So each time when it was a chance to retry a failed job, a new job was run :)   

Thanks a lot, now it works!

**Comment by azygis** [comment] 2023-08-31 07:26
Thank you, @dmitry-vychikov! Closing the issue as it's resolved by configuration changes. Learned something myself as well.

**Closed by azygis** 2023-08-31 07:26 UTC
