### ISSUE TITLE
PGVector problem

### ISSUE THREAD

**Issue by MBrekhof** [hangfire-postgres/Hangfire.PostgreSql#316] opened 2023-08-17 21:14 UTC
I have an Blazor Web app that uses EF Core 7 with Postgresql 15 and the PGVector extension installed (https://github.com/pgvector/pgvector). This all works great using ' options.UseNpgsql(connectionString, o => o.UseVector()).UseLowerCaseNamingConvention();' to configure my DBContext.

However as soon as I add Hangfire using:
        services.AddHangfire(config => config.UsePostgreSqlStorage(hfconnectionString));
        services.AddHangfireServer();

I get this error:
23:04:17:442	SELECT c.codeobjectid, c.codeobjectcategoryid, c.codeobjectcontent, c.subject, c.tokens, c.vectordatastring, c0.codeobjectcategoryid, c0.category
23:04:17:442	FROM codeobject AS c
23:04:17:442	INNER JOIN codeobjectcategory AS c0 ON c.codeobjectcategoryid = c0.codeobjectcategoryid
23:04:17:694	Exception thrown: 'System.InvalidCastException' in Npgsql.dll
23:04:17:694	Exception thrown: 'System.InvalidCastException' in Npgsql.dll
23:04:17:694	Microsoft.EntityFrameworkCore.Query: Error: An exception occurred while iterating over the results of a query for context type 'DocGPT.Module.BusinessObjects.DocGPTEFCoreDbContext'.
**23:04:17:694	System.InvalidCastException: Can't cast database type .<unknown> to Vector**
23:04:17:694	   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ReadCustom[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
23:04:17:694	   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
23:04:17:694	   at lambda_method628(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
23:04:17:694	   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
23:04:17:694	
23:04:17:694	System.InvalidCastException: Can't cast database type .<unknown> to Vector
23:04:17:694	   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ReadCustom[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
23:04:17:694	   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
23:04:17:694	   at lambda_method628(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
23:04:17:694	   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
23:04:17:945	Exception thrown: 'System.InvalidCastException' in Microsoft.EntityFrameworkCore.Relational.dll
23:04:17:945	Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Can't cast database type .<unknown> to Vector
23:04:17:945	
**23:04:17:945	System.InvalidCastException: Can't cast database type .<unknown> to Vector**
23:04:17:945	   at Npgsql.Internal.TypeHandling.NpgsqlTypeHandler.ReadCustom[TAny](NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
23:04:17:945	   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
23:04:17:945	   at lambda_method628(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
23:04:17:945	   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
23:04:17:945	   at DevExpress.EntityFrameworkCore.Security.Query.EnumerableDecorator`1.EnumeratorDecorator.MoveNext()
23:04:17:945	   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
23:04:17:945	   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
23:04:17:945	   at DevExpress.ExpressApp.EFCore.EFCoreCollection.Init()
23:04:17:945	   at DevExpress.ExpressApp.EFCore.EFCoreCollection.get_InnerList()
23:04:17:945	   at DevExpress.ExpressApp.EFCore.EFCoreCollection.get_Count()
23:04:17:945	   at DevExpress.ExpressApp.ProxyCollection.get_Count()
23:04:17:945	   at DevExpress.Data.DataControllerBase.ResetValidateBindingListChangedConsistency(Boolean isSubscribe)

Same query (totaly unrelated to Hangfire) works great when I disable Hangfire and the Hangfire.Postgresql.

Any ideas how to try and solve this?

**Comment by azygis** [comment] 2023-08-17 22:34
Nothing in the stack trace indicates anything Hangfire-related which makes me think it's XY problem, or that maybe you're using EF drop create database migrations, which in turn doesn't work out too well since the database can get created by this provider first before EF migrations.

Can you provide
- startup logs;
- runnable reproduction?

**Comment by MBrekhof** [comment] 2023-08-18 21:59
[hangfire_startup.txt](https://github.com/hangfire-postgres/Hangfire.PostgreSql/files/12384169/hangfire_startup.txt)
This is the startup log, not using migrations. As you can see it runs until I navigate to an entity that has a vector datatype in the table definition. I also included my startup.cs just in case.
[Startup - Copy.cs.txt](https://github.com/hangfire-postgres/Hangfire.PostgreSql/files/12384196/Startup.-.Copy.cs.txt)

**Comment by dmitry-vychikov** [comment] 2023-08-23 20:01
@MBrekhof 

I looked through Hangfire.Postgres source code, but I couldn't find any places that could be potentially causing this issue.

PgVector uses Npgsql extensions to add new handlers  which allows it to support deserealization of their custom`Vector` type. Extension registration is done via `UseVector` extension method (https://github.com/pgvector/pgvector-dotnet/blob/master/src/Pgvector/Npgsql/VectorExtensions.cs#L7-L11).

Since all Npgsql extensions are registered on a `global static object`, any other library could potentially break this by registering something on top of it or even removing older registrations. But I do not see hangfire even touching that `NpgsqlConnection.GlobalTypeMapper` object.


@MBrekhof  can you try the following?

- Change registration order for `Hangfire` and `DbContext` services. Try putting Hangfire first.
    - If Hangfire somehow removes Vector type mappings, then it can probably be solved if you add them after hanfire has been initialized
- Save `NpgsqlConnection.GlobalTypeMapper` to a local variable at the end of your Startup file. Run it with a debugger and inspect what Extensions are registered there. Look for `Vector` extension. We need to make sure it is registered correctly.

**Comment by MBrekhof** [comment] 2023-08-24 03:51
Hi,
Thanks for taking time to look at this. I am going on a short holiday so I will not be able to look at this problem for some time. However I decided to try and solve this problem by giving Hangfire its own webservice, this should make this problem go away without having to go to deep into the problem of the npgsql connection.
regards,
Martin

**Comment by azygis** [comment] 2023-08-24 08:41
Closing the issue as the type mappings are not explicitly changed anywhere in Hangfire.PostgreSql. If trying the suggested changes and/or moving to a separate service doesn't help, you can reopen it.

**Closed by azygis** 2023-08-24 08:41 UTC

**Comment by Tekaichi** [comment] 2024-04-06 19:20
I just had the same issue happened to me.

I was using hangfire.InMemoryStorage and as soon as I switch to PostresSQL, PgVector vector properties seem to be causing this "invalid cast exception".
The culprit is for sure Hangfire.PostgreSql.

I also attempted @MBrekhof suggestion
"Change registration order for Hangfire and DbContext services. Try putting Hangfire first.
If Hangfire somehow removes Vector type mappings, then it can probably be solved if you add them after hanfire has been initialized"
but didnt work

**Comment by azygis** [comment] 2024-04-06 19:38
> The culprit is for sure Hangfire.PostgreSql.

Can't see how it's _for sure_, sorry. This package depends on both Npgsql and Dapper which have their own intristicts about mapping.

We do nothing with geometry or special type mappings, at all. It's all happening on Npgsql side. There is a discussion in a linked issue #322 which shows how we can workaround the problem in the last messages, but that has not been done yet and I have no time for it currently.

There's also [another workaround mentioned](https://github.com/hangfire-postgres/Hangfire.PostgreSql/issues/162#issuecomment-671044622), maybe you can try that as well to some extent.
